#ifndef __MSM8610_H
#define __MSM8610_H

enum target_subtype {
	HW_PLATFORM_SUBTYPE_720P = 0,
	HW_PLATFORM_SUBTYPE_SKUAA = 1,
	HW_PLATFORM_SUBTYPE_SKUF = 2,
	HW_PLATFORM_SUBTYPE_1080P = 2,
	HW_PLATFORM_SUBTYPE_SKUAB = 3,
	HW_PLATFORM_SUBTYPE_1080P_EXT_BUCK = 3,
	HW_PLATFORM_SUBTYPE_QVGA = 4,
	HW_PLATFORM_SUBTYPE_SKUG = 5,
};

unsigned board_machtype(void);

#endif
