# top level project rules for the msm8960_virtio project
#
LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := msm8960

MODULES += \
	app/aboot \
	app/menu

ifeq ($(TARGET_BUILD_VARIANT),user)
DEBUG := 0
else
DEBUG := 1
endif
EMMC_BOOT := 1

#GLOBAL_DEFINES += WITH_DEBUG_DCC=1
GLOBAL_DEFINES += WITH_DEBUG_UART=1
GLOBAL_DEFINES += WITH_DEBUG_LOG_BUF=1
#GLOBAL_DEFINES += WITH_DEBUG_FBCON=1
GLOBAL_DEFINES += DEVICE_TREE=1
GLOBAL_DEFINES += DEVICE_TREE_FALLBACK=1
GLOBAL_DEFINES += ABOOT_IGNORE_BOOT_HEADER_ADDRS=1

GLOBAL_DEFINES += ABOOT_FORCE_KERNEL_ADDR=0x80208000
GLOBAL_DEFINES += ABOOT_FORCE_RAMDISK_ADDR=0x82200000
GLOBAL_DEFINES += ABOOT_FORCE_TAGS_ADDR=0x80200100
GLOBAL_DEFINES += ABOOT_FORCE_KERNEL64_ADDR=0x80208000

#Disable thumb mode
#TODO: The gold linker has issues generating correct
#thumb interworking code for LK. Confirm that the issue
#is with the linker and file a bug rep
ENABLE_THUMB := false

ifeq ($(EMMC_BOOT),1)
GLOBAL_DEFINES += _EMMC_BOOT=1
endif
