LOCAL_DIR := $(GET_LOCAL_DIR)

MODULE := $(LOCAL_DIR)

MODULE_DEPS += \
	lib/ext4 \
	lib/tar \
	app/aboot/uboot_api

GLOBAL_INCLUDES += $(LOCAL_DIR)/include

GLOBAL_DEFINES += ASSERT_ON_TAMPER=1

MODULE_SRCS += \
	$(LOCAL_DIR)/aboot.c \
	$(LOCAL_DIR)/fastboot.c \
	$(LOCAL_DIR)/recovery.c \
	$(LOCAL_DIR)/grub.c
	
GLOBAL_DEFINES += GRUB_LOADING_ADDRESS=$(GRUB_LOADING_ADDRESS)
GLOBAL_DEFINES += GRUB_LOADING_ADDRESS_VIRT=$(GRUB_LOADING_ADDRESS_VIRT)
ifneq ($(GRUB_BOOT_PARTITION),)
GLOBAL_CFLAGS += -DGRUB_BOOT_PARTITION=\"$(GRUB_BOOT_PARTITION)\"
GLOBAL_CFLAGS += -DGRUB_BOOT_PATH_PREFIX=\"$(GRUB_BOOT_PATH_PREFIX)\"
endif

ifeq ($(ENABLE_2NDSTAGE_BOOT),1)
GLOBAL_DEFINES += BOOT_2NDSTAGE=1

MODULE_SRCS += $(LOCAL_DIR)/2ndstage_tools.c
endif

ifneq ($(SPLASH_PARTITION_NAME),)
GLOBAL_CFLAGS += -DSPLASH_PARTITION_NAME=$(SPLASH_PARTITION_NAME)
else
GLOBAL_CFLAGS += -DSPLASH_PARTITION_NAME=\"splash\"
endif


include make/module.mk
